### PR TITLE
Update src/Lobbies to migrate it to new infrastructure

### PR DESCRIPTION
**Pull request by ThetaHalo**
🔥

### CODE REVIEW

**Comment by ThetaHalo** [comment]
@discus-sions lmk if i need any other changes or if its good

**Comment by discus-sions** [comment]
I suggest you convert the list<string> into an int.
```csharp
public static readonly List<string> lobbyPosted = new();
````
```csharp
internal static int CurrentHostedLobby = int.MaxValue;
```

I actually recommend you rewrite that whole function.
You can check for response code and error handling.
```csharp
internal static void POSTModdedLobby(int gameId, string host)
    {
        HttpRequestMessage requestMessage = new();
        requestMessage.RequestUri = new Uri(LobbyEndpoint);
        requestMessage.Method = HttpMethod.Post;
        requestMessage.Headers.Add("game-id", gameId.ToString());
        Version.Version version = VersionControl.Instance.Version ?? new NoVersion();
        requestMessage.Headers.Add("game-code", GameCode.IntToGameNameV2(gameId));
        requestMessage.Headers.Add("version", version.ToSimpleName());
        requestMessage.Headers.Add("mod-name", Vents.AssemblyNames[Vents.RootAssemby]);
        requestMessage.Headers.Add("host", SpecialCharacterRegex.Replace(host.Replace(" ", "-"), ""));
        requestMessage.Headers.Add("region", ServerManager.Instance.CurrentRegion.Name);
        Client.SendAsync(requestMessage);
    }
```
```csharp
internal static IEnumerator POSTModdedLobby(int gameId, string host)
    {
        HttpRequestMessage requestMessage = new();
        requestMessage.RequestUri = new Uri(LobbyEndpoint);
        requestMessage.Method = HttpMethod.Post;
        requestMessage.Headers.Add("game-id", gameId.ToString());
        Version.Version version = VersionControl.Instance.Version ?? new NoVersion();
        requestMessage.Headers.Add("game-code", GameCode.IntToGameNameV2(gameId));
        requestMessage.Headers.Add("version", version.ToSimpleName());
        requestMessage.Headers.Add("mod-name", Vents.AssemblyNames[Vents.RootAssemby]);
        requestMessage.Headers.Add("host", SpecialCharacterRegex.Replace(host.Replace(" ", "-"), ""));
        requestMessage.Headers.Add("region", ServerManager.Instance.CurrentRegion.Name);
        HttpResponseMessage response;
        try
        {
            response = await Client.SendAsync(requestMessage);

            int statusCode = (int)response.StatusCode;
            // or do this
            bool isOk = response.StatusCode.HasFlag(HttpStatusCode.OK)
        }
        catch (HttpRequestException e)
        {
            log.Exception($"Request error", e);
        }

        yield return null;
    }
```

**Comment by ThetaHalo** [comment]
> I suggest you convert the list into an int.
> 
> ```cs
> public static readonly List<string> lobbyPosted = new();
> ```
> 
> ```cs
> internal static int CurrentHostedLobby = int.MaxValue;
> ```
> 
> I actually recommend you rewrite that whole function. You can check for response code and error handling.

remade function in unitywebrequest so i could add error handling, hope its good now

**Comment by discus-sions** [comment]
Did you mean to remove lobbyPosted?
image

Also please use `Async.Execute` instead of `__instance.StartCoroutine`.

**Comment by ThetaHalo** [comment]
> Did you mean to remove lobbyPosted? image

image

> Also please use `Async.Execute` instead of `__instance.StartCoroutine`.

mb fixed

**Comment by discus-sions** [comment]
I think that's everything. Thank you!

**Pull request merged**
